[deps]
aiohttp = ""
fsspec = ""
gcc = ">=12.1.0"
requests = ""
python = "<3.11"

[pip.deps]
pynwb = "<3"
hdmf = ">3.8,<4"
h5py = "!=3.12.0" # 3.12.0 has windows import issues. Same error for ALL conda versions on windows.
